baseURL = 'https://trivorak.github.io/'
languageCode = 'en-us'
title = 'trivorak'
theme="contrast-hugo"

[Params]
	minimal = false
[menu]
	[[menu.main]]
		identifier = "about"
		name = "About"
		url = "/about/"
		weight = 10
